package hibernate.model;
// Generated 3/12/2013 10:59:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Curriculim generated by hbm2java
 */
public class Curriculim  implements java.io.Serializable {


     private int idCurriculim;
     private String descripcion;
     private String referencia;
     private Set usuarios = new HashSet(0);

    public Curriculim() {
    }

	
    public Curriculim(int idCurriculim, String referencia) {
        this.idCurriculim = idCurriculim;
        this.referencia = referencia;
    }
    public Curriculim(int idCurriculim, String descripcion, String referencia, Set usuarios) {
       this.idCurriculim = idCurriculim;
       this.descripcion = descripcion;
       this.referencia = referencia;
       this.usuarios = usuarios;
    }
   
    public int getIdCurriculim() {
        return this.idCurriculim;
    }
    
    public void setIdCurriculim(int idCurriculim) {
        this.idCurriculim = idCurriculim;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


