package hibernate.model;
// Generated 3/12/2013 10:59:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empleo generated by hbm2java
 */
public class Empleo  implements java.io.Serializable {


     private int idEmpleo;
     private Habilidades habilidades;
     private String nombre;
     private String descripcion;
     private Set empresaempleos = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Empleo() {
    }

	
    public Empleo(int idEmpleo, Habilidades habilidades, String nombre) {
        this.idEmpleo = idEmpleo;
        this.habilidades = habilidades;
        this.nombre = nombre;
    }
    public Empleo(int idEmpleo, Habilidades habilidades, String nombre, String descripcion, Set empresaempleos, Set usuarios) {
       this.idEmpleo = idEmpleo;
       this.habilidades = habilidades;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.empresaempleos = empresaempleos;
       this.usuarios = usuarios;
    }
   
    public int getIdEmpleo() {
        return this.idEmpleo;
    }
    
    public void setIdEmpleo(int idEmpleo) {
        this.idEmpleo = idEmpleo;
    }
    public Habilidades getHabilidades() {
        return this.habilidades;
    }
    
    public void setHabilidades(Habilidades habilidades) {
        this.habilidades = habilidades;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEmpresaempleos() {
        return this.empresaempleos;
    }
    
    public void setEmpresaempleos(Set empresaempleos) {
        this.empresaempleos = empresaempleos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


