package hibernate.model;
// Generated 3/12/2013 10:59:37 AM by Hibernate Tools 3.2.1.GA



/**
 * EmpresaempleoId generated by hbm2java
 */
public class EmpresaempleoId  implements java.io.Serializable {


     private int usuarioIdusuario;
     private int empleoIdEmpleo;

    public EmpresaempleoId() {
    }

    public EmpresaempleoId(int usuarioIdusuario, int empleoIdEmpleo) {
       this.usuarioIdusuario = usuarioIdusuario;
       this.empleoIdEmpleo = empleoIdEmpleo;
    }
   
    public int getUsuarioIdusuario() {
        return this.usuarioIdusuario;
    }
    
    public void setUsuarioIdusuario(int usuarioIdusuario) {
        this.usuarioIdusuario = usuarioIdusuario;
    }
    public int getEmpleoIdEmpleo() {
        return this.empleoIdEmpleo;
    }
    
    public void setEmpleoIdEmpleo(int empleoIdEmpleo) {
        this.empleoIdEmpleo = empleoIdEmpleo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpresaempleoId) ) return false;
		 EmpresaempleoId castOther = ( EmpresaempleoId ) other; 
         
		 return (this.getUsuarioIdusuario()==castOther.getUsuarioIdusuario())
 && (this.getEmpleoIdEmpleo()==castOther.getEmpleoIdEmpleo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioIdusuario();
         result = 37 * result + this.getEmpleoIdEmpleo();
         return result;
   }   


}


