package hibernate.model;
// Generated 3/12/2013 10:59:37 AM by Hibernate Tools 3.2.1.GA



/**
 * Empresaempleo generated by hbm2java
 */
public class Empresaempleo  implements java.io.Serializable {


     private EmpresaempleoId id;
     private Empleo empleo;
     private Usuario usuario;
     private int salario;

    public Empresaempleo() {
    }

    public Empresaempleo(EmpresaempleoId id, Empleo empleo, Usuario usuario, int salario) {
       this.id = id;
       this.empleo = empleo;
       this.usuario = usuario;
       this.salario = salario;
    }
   
    public EmpresaempleoId getId() {
        return this.id;
    }
    
    public void setId(EmpresaempleoId id) {
        this.id = id;
    }
    public Empleo getEmpleo() {
        return this.empleo;
    }
    
    public void setEmpleo(Empleo empleo) {
        this.empleo = empleo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getSalario() {
        return this.salario;
    }
    
    public void setSalario(int salario) {
        this.salario = salario;
    }




}


