package hibernate.model;
// Generated 3/12/2013 10:59:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Habilidades generated by hbm2java
 */
public class Habilidades  implements java.io.Serializable {


     private int idHabilidades;
     private Tipohabilidad tipohabilidad;
     private String nombre;
     private Set usuarios = new HashSet(0);
     private Set empleos = new HashSet(0);

    public Habilidades() {
    }

	
    public Habilidades(int idHabilidades, Tipohabilidad tipohabilidad, String nombre) {
        this.idHabilidades = idHabilidades;
        this.tipohabilidad = tipohabilidad;
        this.nombre = nombre;
    }
    public Habilidades(int idHabilidades, Tipohabilidad tipohabilidad, String nombre, Set usuarios, Set empleos) {
       this.idHabilidades = idHabilidades;
       this.tipohabilidad = tipohabilidad;
       this.nombre = nombre;
       this.usuarios = usuarios;
       this.empleos = empleos;
    }
   
    public int getIdHabilidades() {
        return this.idHabilidades;
    }
    
    public void setIdHabilidades(int idHabilidades) {
        this.idHabilidades = idHabilidades;
    }
    public Tipohabilidad getTipohabilidad() {
        return this.tipohabilidad;
    }
    
    public void setTipohabilidad(Tipohabilidad tipohabilidad) {
        this.tipohabilidad = tipohabilidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getEmpleos() {
        return this.empleos;
    }
    
    public void setEmpleos(Set empleos) {
        this.empleos = empleos;
    }




}


