package hibernate.model;
// Generated 3/12/2013 10:59:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipohabilidad generated by hbm2java
 */
public class Tipohabilidad  implements java.io.Serializable {


     private int idTipoHabilidad;
     private String nombre;
     private Set habilidadeses = new HashSet(0);

    public Tipohabilidad() {
    }

	
    public Tipohabilidad(int idTipoHabilidad) {
        this.idTipoHabilidad = idTipoHabilidad;
    }
    public Tipohabilidad(int idTipoHabilidad, String nombre, Set habilidadeses) {
       this.idTipoHabilidad = idTipoHabilidad;
       this.nombre = nombre;
       this.habilidadeses = habilidadeses;
    }
   
    public int getIdTipoHabilidad() {
        return this.idTipoHabilidad;
    }
    
    public void setIdTipoHabilidad(int idTipoHabilidad) {
        this.idTipoHabilidad = idTipoHabilidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getHabilidadeses() {
        return this.habilidadeses;
    }
    
    public void setHabilidadeses(Set habilidadeses) {
        this.habilidadeses = habilidadeses;
    }




}


