package hibernate.model;
// Generated 3/12/2013 10:59:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private Curriculim curriculim;
     private Tipousuario tipousuario;
     private String name;
     private String password;
     private String email;
     private Integer age;
     private String phone;
     private String contacto;
     private String description;
     private String usuariocol;
     private Set empresaempleos = new HashSet(0);
     private Set habilidadeses = new HashSet(0);
     private Set empleos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, Curriculim curriculim, Tipousuario tipousuario, String name, String password, String email) {
        this.idusuario = idusuario;
        this.curriculim = curriculim;
        this.tipousuario = tipousuario;
        this.name = name;
        this.password = password;
        this.email = email;
    }
    public Usuario(int idusuario, Curriculim curriculim, Tipousuario tipousuario, String name, String password, String email, Integer age, String phone, String contacto, String description, String usuariocol, Set empresaempleos, Set habilidadeses, Set empleos) {
       this.idusuario = idusuario;
       this.curriculim = curriculim;
       this.tipousuario = tipousuario;
       this.name = name;
       this.password = password;
       this.email = email;
       this.age = age;
       this.phone = phone;
       this.contacto = contacto;
       this.description = description;
       this.usuariocol = usuariocol;
       this.empresaempleos = empresaempleos;
       this.habilidadeses = habilidadeses;
       this.empleos = empleos;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Curriculim getCurriculim() {
        return this.curriculim;
    }
    
    public void setCurriculim(Curriculim curriculim) {
        this.curriculim = curriculim;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUsuariocol() {
        return this.usuariocol;
    }
    
    public void setUsuariocol(String usuariocol) {
        this.usuariocol = usuariocol;
    }
    public Set getEmpresaempleos() {
        return this.empresaempleos;
    }
    
    public void setEmpresaempleos(Set empresaempleos) {
        this.empresaempleos = empresaempleos;
    }
    public Set getHabilidadeses() {
        return this.habilidadeses;
    }
    
    public void setHabilidadeses(Set habilidadeses) {
        this.habilidadeses = habilidadeses;
    }
    public Set getEmpleos() {
        return this.empleos;
    }
    
    public void setEmpleos(Set empleos) {
        this.empleos = empleos;
    }




}


